### PR TITLE
Set WRT option (WOFOST)

### PR DESCRIPTION
**Pull request by julienmalard**
Added set_variable option for dry root weight (WRT) in WOFOST model.

### CODE REVIEW

**Comment by julienmalard** [comment]
Please let me know as well if there is a good place to add this to the documentation.

**Comment by julienmalard** [comment]
I would also be interesting in contributing for SAI/PAI, but was unsure of the technical details as changes to these would also (I believe?) need to change LAI in the leaf dynamics module (unless LAI is calculated automatically?).

**Comment by ajwdewit** [comment]
Hi Julien,

sorry for the late response, but I do not want to merge this directly into the master branch. The proper place to merge this would be the develop branch. I am closing this now but please send an new pull request for merging into develop rather than master.

with best regards,
Allard

**Comment by julienmalard** [comment]
Hello,
No problem; I just submitted a separate pull request to the master branch.
Best,
Julien Malard

**Pull request closed without merging**
