### PR TITLE
Fixing fill value

### PR DESCRIPTION
**Pull request by LeaTresch**
Hi!
I cloned the repo in order to use PCSE with the new NASA Power API. However, it's not usable as it is because of a KeyError in line 318 of nasapower.py (folder pcse/db).
The dictionnary `powerdata["header"]` has a key name `fill_value` and not `fillValue`. 
I executed the class `NASAPowerWeatherDataProvider` with the right key and everything seems to work! I tried it on the master branch.
Thanks!
Léa

### CODE REVIEW

**Comment by Amarounek** [comment]
With `fill_value`, I am getting `TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'`.

I cannot find the mistake

**Comment by ajwdewit** [comment]
Thanks for bringing this up. I will have a look at the NASApower weatherdataprovider because I see some confusing behaviour that I have to sort out first.

Allard

**Comment by mishagrol** [comment]
@Amarounek perhaps this error is caused by the fact that the NASA POWER API returns NaN values for the PRECTOTCORR parameter for all dates, and the NASAPowerWeatherDataProvider class removes rows from pandas df if there is a NaN, the result is an empty pandas df.

I sent a mail to NASA, and they promised to return the Daily precipitation parameter: 

> We are planning to have the Daily precipitation back online in a week or less. 


> 
> TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
> ```

**Comment by Amarounek** [comment]
@mishagrol Thanks for the suggestion! I was just trying the updated PCSE remotely and on local machine and now it is running fine. Don't know where the issue was...

**Comment by ajwdewit** [comment]
I just updated PCSE to 5.5.0 and as far as I can see the NASAPowerWeatherDataProvider works, it includes the fix on the fill value. Give it a try if you like.

**Pull request closed without merging**
